### ISSUE TITLE
Tracking: "atomic" "continuous" interval with comparer.

### ISSUE THREAD

**Issue by SingleAccretion** [SingleAccretion/Accretion.Intervals#9]
## Definition
- [x] `Empty`:
````C#
public static Interval<T, TComparer> Empty { get; }
````
- [x] `IsEmpty`: default value is `true`.
````C#
public bool IsEmpty { get; }
````
- [x] `Contains`:
````C#
public bool Contains(T value);
````
- [x] `IEquatable<T>`: implicit implementation.
- [x] `Equals`: value semantics.
- [x] `GetHashCode`: value semantics.

## Implementation
- [x] `Empty`
- [ ] `IsEmpty`
- [ ] `Contains`
- [ ] `Equals`
- [ ] `GetHashCode`

## Tests
- With `System.Double` as a type argument and a custom comparer:
  - [ ] `IsEmpty`
  - [ ] `Contains`
  - [ ] `Equals`
  - [ ] `GetHashCode`
- With custom class as a type argument and a custom comparer:
  - [ ] `IsEmpty`
  - [ ] `Contains`
  - [ ] `Equals`
  - [ ] `GetHashCode`

## XML documentation
- [ ] `Empty`
- [ ] `IsEmpty`
- [ ] `Contains`
- [ ] `Equals`
- [ ] `GetHashCode`

## Proper documentation
- [ ] `Empty`
- [ ] `IsEmpty`
- [ ] `Contains`
- [ ] `Equals`
- [ ] `GetHashCode`
